In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
from pathlib import Path
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid
import cv2
import numpy as np
import imutils
import random
import pickle

In [3]:
data_dir = Path.cwd() / "EnsembleB"

# A list of string with all the categories/labels in your database, i.e., each class subfolder name
LABELS = ["Cercles2", "Cercles5", "Hexagones2","Hexagones5", "Triangles2","Triangles5" ,"Diamants2", "Diamants5"]

In [4]:
# Image resize
WIDTH = 160
HEIGHT = 70

# Dataset: this list will contain all the images
data_set = []

In [6]:
for first_level in data_dir.glob('*'):
    if first_level.is_dir():
        for sec_level in first_level.glob('*'):
            label = sec_level.name
            if label in LABELS:
                class_num = LABELS.index(label)
                print(f"{label} {class_num}")
                for image_path in sec_level.glob('*'):
                    # Lire l'image avec OpenCV
                    image = cv2.imread(str(image_path))
                    #print(image)
                    
                    # Si l'image est chargée correctement
                    if image is not None:
                        # Redimensionner l'image si nécessaire
                        resized_image = cv2.resize(image, (WIDTH, HEIGHT))
                        print(resized_image)
                        print(image)
                        
                        # Ajouter les informations à data_set
                        data_set.append([resized_image, class_num, label])

Cercles5 1
[[[ 19  19  19]
  [ 25  25  25]
  [ 25  25  25]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 28  28  28]
  [ 35  35  35]
  [ 39  39  39]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 91  91  91]
  [ 37  37  37]
  [ 56  56  56]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 ...

 [[102 102 102]
  [100 100 100]
  [ 90  90  90]
  ...
  [ 82  82  82]
  [ 80  80  80]
  [ 74  74  74]]

 [[108 108 108]
  [ 95  95  95]
  [ 92  92  92]
  ...
  [ 72  72  72]
  [ 72  72  72]
  [ 72  72  72]]

 [[130 130 130]
  [ 91  91  91]
  [ 99  99  99]
  ...
  [ 73  73  73]
  [ 71  71  71]
  [ 69  69  69]]]
[[[ 17  17  17]
  [ 19  19  19]
  [ 22  22  22]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 17  17  17]
  [ 20  20  20]
  [ 24  24  24]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 [[ 17  17  17]
  [ 22  22  22]
  [ 27  27  27]
  ...
  [ 10  10  10]
  [ 10  10  10]
  [ 10  10  10]]

 ...

 [[146 146 146]
  [ 99  99  99]
  [ 86  8